name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploying to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.VPS_SSH_KEY }}
        script: |
          sudo su root
          cd /home/root/dev/fcit18Link/FCIT18.link_URL/
          sudo git pull origin main
          sudo python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          deactivate
          sudo systemctl restart fcit18link